[package]
name = "swc_plugin_raw_macro"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1"
serde_json = "1.0.79"
swc_ecma_visit = "0.71.1"
swc_plugin = "0.80.2"
wasmedge-wasi-helper = "0.2.0"
