[package]
name = "swc_plugin_raw_macro"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
serde = "1"
serde_json = "1.0.79"
swc_core = { version = "0.29.*", features = ["plugin_transform"] }
